//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palantir.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palantir.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg id=&quot;Ebene_1&quot; data-name=&quot;Ebene 1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;500&quot; height=&quot;333.46809&quot; viewBox=&quot;0 0 500 333.46809&quot;&gt; &lt;defs&gt; &lt;style&gt;$customstyle$ .{}.cls-1, .cls-21{fill: none;}.cls-2{fill: #18191c;}.cls-3{clip-path: url(#clip-path);}.cls-4, .cls-7{fill: #36a9e1;}.cls-21, .cls-4, .cls-7{stroke: #36a9e1;}.cls-4{stroke-linecap: square;}.cls-18, .cls-19, .cls-21, .cls-4, .cls-7{stroke-miterlimit: 10;}.cls-21, .cls-4{stroke-width: 8px;}.cls-5{font-size:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SVGcard {
            get {
                return ResourceManager.GetString("SVGcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg id=&quot;Ebene_1&quot; data-name=&quot;Ebene 1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; viewBox=&quot;0 0 520.27 332.48&quot;&gt; &lt;defs&gt; &lt;style&gt;.cls-1, .cls-21{fill: none;}.cls-2{fill: #18191c;}.cls-3{clip-path: url(#clip-path);}.cls-4{clip-path: url(#clip-path-2);}.cls-5, .cls-8{fill: #36a9e1;}.cls-21, .cls-5, .cls-8{stroke: #36a9e1;}.cls-5{stroke-linecap: square;}.cls-19, .cls-20, .cls-21, .cls-5, .cls-8{stroke-miterlimit: 10;}.cls-21, .cls-5{stroke-width: 8px;}.cls-12, .cls-13, .cls-14, .c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SVGcardBG {
            get {
                return ResourceManager.GetString("SVGcardBG", resourceCulture);
            }
        }
    }
}
